version: '3.8'

services:
  app:
    build: .
    container_name: url_shortener_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=database
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=urlshortener
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=password
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
    depends_on:
      - database
    networks:
      - url_shortener_network

  database:
    image: mongo:latest
    container_name: db_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - url_shortener_network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  url_shortener_network:
    driver: bridge
